**Khái quát:**

+ **torch.tensor(*data*)** : Chuyển dạng list, matrix thành 1 tensor (Cấu trúc tương tự)
+ **torch.form_numpy(*np_data*)** : Chuyển dạng numpyarray thành 1 tensor
+ **torch.rand_like(*x_tensor*, dtype=torch.float)** : Tạo 1 tensor với các phần tử mang giá trị random thuộc kiểu *torch.float* với tensor mới có cùng kích thước với *x_tensor*
+ **torch.ones_like(x_tensor) / torch.zeros_like(x_tesnor)** : Tương tự như torch.rand_like(...) như ones_like tạo tensor có các phần tử là 1, zeros_like tạo tensor có các phần tử là 0
+ **torch.rand((H, W)) / torch.ones((H, W)) / torch.zeros((H, W))** : Tạo 1 tensor có kích thước (H, W)
+ **x_tensor.shape / x_tensor.dtype / x_tensor.device** : Lấy kích thước / kiểu dữ liệu / vị trí lưu của x_tensor
+ **x_tensor[a, b] / x_tensor[:, 1] / x_tensor[1, :]** : Lấy / thay đổi các phần tử trong x_tensor
+ **torch.cat(tensor_1, tensor_2, ..., dim=0)** : stack các tensor_1, tensor_2, ... theo: dim=0: stack theo vertical, dim=1: stack theo horizal
+ **tensor_1 @ tensor_2 / torch.matmul(tensor_1, tensor_2)** : Phép nhân ma trận cho 2 tensor
+ **tensor_1 * tensor_2 / torch.mul(tensor_1, tensor_2)** : Phép nhân từng phần tử cùng index trong tensor_1 và tensor_2
+ **x_tensor.add_(2)** : Tăng tất cả các phần tử trong tensor lên 2 đơn vị
+ **x_tensor.sum()** : Tạo 1 tensor có 1 phần tử với giá trị là tổng các phần tử của x_tensor
+ **x_tensor.item()** : Chuyển tensor 1 phần tử thành Python numarical value
+ **x_tensor.numpy()** : Chuyển tensor thành numpyarray 

***Lưu ý***; Nếu dùng các hàm chuyển đổi giữa Tensor thành Numpyarray, thay đổi giá trị các phần tử trong x_tensor thì numpyarray được chuyển trước đó cũng thay đổi và ngược lại


In [45]:
import torch
import numpy as np

# **Introduce to Tensor**

In [46]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [47]:
np_data = np.array(data)
X_data_fr_np = torch.from_numpy(np_data)
X_data_fr_np

tensor([[1, 2],
        [3, 4]])

In [48]:
x_ones = torch.ones_like(x_data)
x_rand = torch.rand_like(x_data, dtype = torch.float)

print(f"One tensor: \n {x_ones}")
print(f"Rand tensor: \n {x_rand}")
print(f"Original tensor: \n {x_data}")

One tensor: 
 tensor([[1, 1],
        [1, 1]])
Rand tensor: 
 tensor([[0.6948, 0.1234],
        [0.1041, 0.2010]])
Original tensor: 
 tensor([[1, 2],
        [3, 4]])


In [49]:
shape = (2, 3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
print(f"rand_tensor = \n {rand_tensor}")
print(f"ones_tensor = \n {ones_tensor}")
print(f"zeros_tensor = \n {zeros_tensor}")

rand_tensor = 
 tensor([[0.1064, 0.1045, 0.1292],
        [0.0833, 0.3021, 0.3761]])
ones_tensor = 
 tensor([[1., 1., 1.],
        [1., 1., 1.]])
zeros_tensor = 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [50]:
rand_tensor = torch.rand((3,2))
print("Shape of rand_tensor:", rand_tensor.shape)
print("Datatype of rand_tensor:", rand_tensor.dtype)
print("Device rand_tensor is stored in:", rand_tensor.device)

Shape of rand_tensor: torch.Size([3, 2])
Datatype of rand_tensor: torch.float32
Device rand_tensor is stored in: cpu


# **Operations on Tensors**

In [51]:
if torch.cuda.is_available():
    print("OK")
    rand_tensor = rand_tensor.to("cuda")

In [52]:
rand_tensor = torch.rand((2, 3))

print(f"Rand_tensor = \n {rand_tensor}")
print("----------------------------------------------")
print("First row:", rand_tensor[0, :])
print("First column:", rand_tensor[:, 0])
print("Last column:", rand_tensor[:, -1])

Rand_tensor = 
 tensor([[0.7442, 0.1113, 0.7643],
        [0.3580, 0.2305, 0.0932]])
----------------------------------------------
First row: tensor([0.7442, 0.1113, 0.7643])
First column: tensor([0.7442, 0.3580])
Last column: tensor([0.7643, 0.0932])


In [53]:
# rand_tensor[1,2] = 1
rand_tensor[:, 2] = 2
print(rand_tensor)

tensor([[0.7442, 0.1113, 2.0000],
        [0.3580, 0.2305, 2.0000]])


In [54]:
# Stack by vertical
multi_tensor = torch.cat([rand_tensor, ones_tensor, zeros_tensor], dim=0)
print(multi_tensor)

# Stack by horizal
multi_tensor = torch.cat([rand_tensor, ones_tensor, zeros_tensor], dim=1)
print(multi_tensor)

tensor([[0.7442, 0.1113, 2.0000],
        [0.3580, 0.2305, 2.0000],
        [1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000]])
tensor([[0.7442, 0.1113, 2.0000, 1.0000, 1.0000, 1.0000, 0.0000, 0.0000, 0.0000],
        [0.3580, 0.2305, 2.0000, 1.0000, 1.0000, 1.0000, 0.0000, 0.0000, 0.0000]])


In [55]:
data = [[1, 2, 3], [4, 5, 6]]
x_tensor = torch.tensor(data)

y1 = x_tensor @ x_tensor.T
y2 = x_tensor.matmul(x_tensor.T)
print(y1)
print(y2)

print("--------------------------------------\n")

z1 = x_tensor * x_tensor
z2 = x_tensor.mul(x_tensor)
print(z1)
print(z2)

tensor([[14, 32],
        [32, 77]])
tensor([[14, 32],
        [32, 77]])
--------------------------------------

tensor([[ 1,  4,  9],
        [16, 25, 36]])
tensor([[ 1,  4,  9],
        [16, 25, 36]])


In [56]:
data = [[0, 1, 1, 1], [1, 0, 1, 1], [1, 1, 0, 1], [1, 1, 1, 0]]
X = torch.tensor(data)
print(X)
X.add_(5)
print(X)

tensor([[0, 1, 1, 1],
        [1, 0, 1, 1],
        [1, 1, 0, 1],
        [1, 1, 1, 0]])
tensor([[5, 6, 6, 6],
        [6, 5, 6, 6],
        [6, 6, 5, 6],
        [6, 6, 6, 5]])


In [57]:
agg = x_tensor.sum()
agg_item = agg.item()
print(agg, type(agg))
print(agg_item, type(agg_item))

tensor(21) <class 'torch.Tensor'>
21 <class 'int'>


In [58]:
# Tensor to numpyarray
x_tensor = torch.ones((2,3))
x_numpy = x_tensor.numpy()
print(x_numpy)
print(type(x_numpy))

# Change x_tensor, x_numpy will change also
x_tensor.add_(2)
print(x_numpy)

[[1. 1. 1.]
 [1. 1. 1.]]
<class 'numpy.ndarray'>
[[3. 3. 3.]
 [3. 3. 3.]]
